project:
  name: "milestone1_ultimate_m2"
  target_f1: 0.94

model:
  name: "roberta-base"
  num_labels: 2
  max_length: 256
  dropout: 0.15

training:
  device: "mps"
  batch_size: 16
  learning_rate: 2e-5
  epochs_per_chunk: 6
  gradient_accumulation_steps: 4
  warmup_steps: 1000
  weight_decay: 0.01
  mixed_precision: true

hardware:
  dataloader_num_workers: 4
  pin_memory: true
  gradient_checkpointing: true

# REQUIRED 'paths' SECTION (this was missing)
paths:
  model_dir: "models/milestone_01/final"
  checkpoint_dir: "models/milestone_01/checkpoints"
  ensemble_dir: "models/milestone_01/ensemble"  
  output_dir: "outputs/milestone1"

data:
  chunks_dir: "data/processed/milestone1"
  train_pattern: "enhanced_ultimate_train_chunk_*.csv"
  test_pattern: "enhanced_ultimate_test_chunk_*.csv"
