# MacBook M2 Optimized Configuration
project:
  name: "milestone1_ultimate_m2"
  target_f1: 0.93

model:
  name: "roberta-base"        # Perfect fit for M2
  num_labels: 2               # Binary classification
  max_length: 256             # Good context window
  dropout: 0.15

training:
  device: "mps"               # Metal Performance Shaders
  batch_size: 16              # Optimal for 8GB unified memory
  learning_rate: 2e-5
  epochs_per_chunk: 6
  gradient_accumulation_steps: 4  # Effective batch = 64
  mixed_precision: true       # Essential for memory efficiency
  gradient_checkpointing: true

hardware:
  dataloader_num_workers: 4   # M2 CPU efficiency
  pin_memory: true
  compile_model: true         # PyTorch 2.0 optimization

data:
  chunks_dir: "data/processed/milestone1"
  train_pattern: "enhanced_ultimate_train_chunk_*.csv"
  test_pattern: "enhanced_ultimate_test_chunk_*.csv"
  num_classes: 2              # Keep binary

paths:
  model_dir: "models/milestone_01/final"
  output_dir: "outputs/milestone1"
