# ULTIMATE MULTIMODAL SARCASM DETECTION CONFIGURATION
# Target: 85%+ F1 Score on RTX 2050

project:
  name: "milestone1-ultimate-sarcasm"
  version: "2.0"
  target_accuracy: 0.85

# Enhanced Chunking Configuration
chunking:
  chunk_size: 1400
  test_split: 0.25
  stratified_split: true
  shuffle_data: true
  cross_validation: false
  enhanced_metadata: true

# Ultimate Training Configuration
training:
  epochs_per_chunk: 10
  batch_size: 4
  learning_rate: 1e-6
  model_name: "roberta-large"
  max_length: 256
  gradient_accumulation_steps: 16  # Effective batch size = 64
  warmup_steps: 2000
  weight_decay: 0.01
  label_smoothing: 0.15
  scheduler: "cosine_annealing_warm_restarts"
  early_stopping: true
  patience: 5

# Advanced Model Architecture
model_architecture:
  text_encoder: "roberta-large"
  image_encoder: "openai/clip-vit-large-patch14"
  audio_encoder: "facebook/wav2vec2-large"
  fusion_method: "hierarchical_cross_attention"
  attention_heads: 16
  hidden_size: 768
  dropout: 0.15
  use_gating: true
  use_residual: true
  dynamic_routing: true
  num_experts: 8
  incongruity_detection: true
  uncertainty_estimation: true

# Dataset Configuration
datasets:
  mustard:
    data_path: "data/multimodal/mustard_bert/"
    modalities: ["text", "audio", "video"]
    weight: 1.0
    domain: "tv_shows"
  sarcnet:
    data_path: "data/multimodal/sarcnet/"
    modalities: ["text", "image"]
    weight: 1.2
    domain: "social_media"
  mmsd2:
    data_path: "data/multimodal/mmsd2/"
    modalities: ["text", "image"]
    weight: 1.5
    domain: "social_media"
  ur_funny:
    data_path: "data/multimodal/ur_funny/"
    modalities: ["text", "video", "audio"]
    weight: 0.8
    domain: "ted_talks"
  spanish_sarcasm:
    data_path: "data/text/spanish_sarcasm/"
    modalities: ["text"]
    weight: 0.6
    domain: "general"

# Paths Configuration
paths:
  chunks_dir: "data/chunks/milestone1_ultimate"
  models_dir: "models/milestone1_ultimate"
  final_model: "models/milestone1_ultimate_ensemble.pt"
  logs_dir: "logs/milestone1_ultimate"
  temp_dir: "temp/milestone1"

# Ultimate Data Augmentation
augmentation:
  enabled: true
  probability: 0.7
  text_augmentation:
    back_translation: true
    back_translation_prob: 0.3
    paraphrasing: true
    paraphrasing_prob: 0.3
    synonym_replacement: true
    synonym_prob: 0.4
    random_insertion: true
    insertion_prob: 0.2
    random_deletion: true
    deletion_prob: 0.2
  image_augmentation:
    enabled: true
    horizontal_flip: 0.5
    vertical_flip: 0.2
    rotation: 0.4
    color_jitter: 0.6
    gaussian_blur: 0.3
    random_crop: 0.4
    cutmix: 0.3
    mixup: 0.2
  audio_augmentation:
    enabled: true
    noise_injection: 0.4
    speed_perturbation: 0.3
    pitch_shift: 0.3
    time_stretch: 0.2

# Synthetic Data Generation
synthetic_data:
  enabled: true
  generation_probability: 0.4
  synthetic_data_ratio: 0.3
  cross_modal_fusion: true
  text_to_image_descriptions: true
  image_to_text_captions: true

# Multi-task Learning
multi_task:
  enabled: true
  sentiment_analysis: true
  sentiment_weight: 0.3
  emotion_recognition: true
  emotion_weight: 0.2
  irony_detection: true
  irony_weight: 0.4

# Domain Adaptation
domain_adaptation:
  enabled: true
  num_domains: 6
  domains: ["tv_shows", "social_media", "ted_talks", "memes", "news", "general"]
  domain_specific_layers: true
  adversarial_training: false

# Advanced Training Strategies
training_strategies:
  curriculum_learning: true
  focal_loss: true
  mixup_alpha: 0.4
  cutmix_alpha: 0.3
  contrastive_learning: true
  contrastive_weight: 0.1
  uncertainty_weighting: true

# RTX 2050 Hardware Optimization
hardware:
  device: "cuda"
  mixed_precision: true
  gradient_checkpointing: true
  compile_model: true
  cuda_memory_fraction: 0.98
  dataloader_num_workers: 4
  pin_memory: true
  persistent_workers: true

# Ensemble Configuration
ensemble:
  enabled: true
  top_k_models: 9
  ensemble_epochs: 12
  ensemble_lr: 2e-6
  ensemble_batch_size: 8
  ensemble_method: "stacking_with_meta_learning"
  cross_validation_ensemble: true
  uncertainty_based_weighting: true

# Logging and Monitoring
logging:
  log_level: "INFO"
  save_logs: true
  log_every_n_steps: 50
  save_checkpoints_every: 2
  wandb:
    enabled: true
    project: "milestone1-ultimate-sarcasm"
    entity: "your-wandb-username"  # Replace with your username
    tags: ["ultimate", "multimodal", "rtx2050", "sarcasm"]
  detailed_logging:
    log_attention_weights: true
    log_domain_metrics: true
    log_language_metrics: true
    log_incongruity_scores: true
    log_uncertainty_estimates: true
    save_confusion_matrices: true
