# Milestone 3: Fact Verification Ensemble Configuration
ensemble:
  top_k_models: 5
  ensemble_epochs: 5
  ensemble_lr: 0.0001
  ensemble_batch_size: 16
  selection_metric: "loss"

paths:
  models_dir: "models/chunk_models"
  final_model: "models/milestone3_fact_verification_ensemble.pt"
  logs_dir: "logs/milestone3"

training:
  model_name: "bert-base-uncased"
  batch_size: 16
  max_length: 512

datasets:
  sarc:
    test_balanced: "data/fact_verification/train_formatted.csv"
    test_unbalanced: "data/fact_verification/train_formatted.csv"

hardware:
  device: "cuda"
