# Chunked Training Configuration for RTX 2050
chunking:
  chunk_size: 2608           # Optimized for ~1 hour GPU training
  test_split: 0.1            # Test split ratio
  shuffle_data: true         # Shuffle data before chunking
  
training:
  epochs_per_chunk: 3        # Training epochs per chunk
  batch_size: 16             # Optimal for 4GB VRAM
  learning_rate: 2e-5        # Standard for multilingual BERT
  model_name: "bert-base-multilingual-cased"  # Supports EN/ZH/ES
  max_length: 512            # Maximum sequence length
  warmup_steps: 0            # Warmup steps for scheduler
  weight_decay: 0.01         # Weight decay regularization
  
ensemble:
  top_k_models: 5            # Number of best models to ensemble
  ensemble_epochs: 5         # Epochs for meta-learner training
  ensemble_lr: 1e-4          # Learning rate for meta-learner
  ensemble_batch_size: 16    # Batch size for ensemble training
  selection_metric: "loss"   # Metric for model selection

datasets:
  sarc:
    train: "data/text/sarc/train-balanced-sarcasm.csv"
    test_balanced: "data/text/sarc/test-balanced.csv"
    test_unbalanced: "data/text/sarc/test-unbalanced.csv"
  headlines:
    data: "data/text/Sarcasm_Headlines_Dataset.json"
  liar:
    train: "data/fact_verification/train.tsv"
    test: "data/fact_verification/test.tsv"
    valid: "data/fact_verification/valid.tsv"
  sarcnet:
    data: "data/multimodal/sarcnet/"
  mmsd2:
    data: "data/multimodal/mmsd2/"
  spanish_sarcasm:
    data: "data/text/spanish_sarcasm/"
  ur_funny:
    data: "data/multimodal/ur_funny/"

paths:
  chunks_dir: "data/chunks"
  models_dir: "models/chunk_models"
  final_model: "models/final_ensemble_model.pt"
  logs_dir: "logs"

# RTX 2050 Optimized Settings
hardware:
  device: "auto"             # auto detects RTX 2050
  mixed_precision: true      # 2x speedup + memory saving
  gradient_checkpointing: true  # Memory optimization for 4GB VRAM
  
# Logging and monitoring
logging:
  log_level: "INFO"
  save_logs: true
  wandb_project: "factcheck-mm-multilingual"  # Optional experiment tracking
